# Generated by Django 4.0.4 on 2022-05-31 19:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acas_part',
            name='measu_prin',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Measurement principle'),
        ),
        migrations.AlterField(
            model_name='acas_part',
            name='measu_prop',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Property Measured'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='info',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Information'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='measu_prin',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Measurement principle'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='measu_prop',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Property Measured'),
        ),
    ]
