# Generated by Django 3.1.3 on 2021-04-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_sp2_xr'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp2_xr',
            name='inlet_air_temp',
            field=models.FloatField(blank=True, db_column='Inlet Air Temperature', null=True),
        ),
        migrations.AddField(
            model_name='sp2_xr',
            name='scatt_peak_time',
            field=models.FloatField(blank=True, db_column='Scatter Peak Time', null=True),
        ),
    ]
