# Generated by Django 3.1.2 on 2020-11-05 04:40

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_ccn_clap_dma_hygrometer_uv_lif'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='primary_variables',
            options={'managed': True, 'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('sensor'), nulls_last=True)], 'verbose_name': 'Variable'},
        ),
        migrations.RenameField(
            model_name='primary_variables',
            old_name='sensor_id',
            new_name='sensor',
        ),
    ]
