# Generated by Django 3.1.3 on 2020-11-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_auto_20201105_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorCpd3Clap',
            fields=[
                ('datetime', models.DateTimeField(db_column='Datetime', primary_key=True, serialize=False)),
                ('transmittance', models.FloatField(blank=True, db_column='Transmittance', null=True)),
                ('aerosol_light_absorption_coefficient', models.FloatField(blank=True, db_column='Aerosol light absorption coefficient', null=True)),
                ('transmittance_b', models.FloatField(blank=True, db_column='Transmittance B', null=True)),
            ],
            options={
                'db_table': 'sensor_cpd3_clap',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SensorCpd3Cpc',
            fields=[
                ('datetime', models.DateTimeField(db_column='Datetime', primary_key=True, serialize=False)),
                ('condensation_nuclei_concentration', models.FloatField(blank=True, db_column='Condensation nuclei concentration', null=True)),
            ],
            options={
                'db_table': 'sensor_cpd3_cpc',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SensorCpd3Neph',
            fields=[
                ('datetime', models.DateTimeField(db_column='Datetime', primary_key=True, serialize=False)),
                ('aerosol_light_scattering_coefficient', models.FloatField(blank=True, db_column='Aerosol light scattering coefficient', null=True)),
            ],
            options={
                'db_table': 'sensor_cpd3_neph',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SensorCpd3PwdVaisala',
            fields=[
                ('datetime', models.DateTimeField(db_column='Datetime', primary_key=True, serialize=False)),
                ('ambient_temperature', models.FloatField(blank=True, db_column='Ambient Temperature', null=True)),
                ('precipitation_rate', models.FloatField(blank=True, db_column='Precipitation Rate', null=True)),
                ('present_weather_flag', models.FloatField(blank=True, db_column='Present Weather Flag', null=True)),
                ('present_weather_code', models.FloatField(blank=True, db_column='Present Weather Code', null=True)),
                ('visibility_distance', models.FloatField(blank=True, db_column='Visibility Distance', null=True)),
            ],
            options={
                'db_table': 'sensor_cpd3_pwd_vaisala',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SensorCpd3WmtVaisala',
            fields=[
                ('datetime', models.DateTimeField(db_column='Datetime', primary_key=True, serialize=False)),
                ('wind_direction', models.FloatField(blank=True, db_column='Wind Direction', null=True)),
                ('wind_speed', models.FloatField(blank=True, db_column='Wind Speed', null=True)),
            ],
            options={
                'db_table': 'sensor_cpd3_wmt_vaisala',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SensorCpd3WxtVaisala',
            fields=[
                ('datetime', models.DateTimeField(db_column='Datetime', primary_key=True, serialize=False)),
                ('ambient_pressure', models.FloatField(blank=True, db_column='Ambient Pressure', null=True)),
                ('ambient_temperature', models.FloatField(blank=True, db_column='Ambient Temperature', null=True)),
                ('ambient_relative_humidity', models.FloatField(blank=True, db_column='Ambient Relative Humidity', null=True)),
                ('solar_radiation', models.FloatField(blank=True, db_column='Solar Radiation', null=True)),
                ('wind_direction', models.FloatField(blank=True, db_column='Wind Direction', null=True)),
                ('precipitation_rate', models.FloatField(blank=True, db_column='Precipitation Rate', null=True)),
                ('wind_speed', models.FloatField(blank=True, db_column='Wind Speed', null=True)),
                ('wind_gust_speed', models.FloatField(blank=True, db_column='Wind Gust Speed', null=True)),
            ],
            options={
                'db_table': 'sensor_cpd3_wxt_vaisala',
                'managed': True,
            },
        ),
    ]
