# Generated by Django 3.1.3 on 2021-05-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_auto_20210512_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uv_lif',
            name='size_of_particle_um_field',
            field=models.FloatField(blank=True, db_column='Size of Particle', null=True),
        ),
    ]
