# Generated by Django 3.1.3 on 2020-11-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_sensorcpd3clap_sensorcpd3cpc_sensorcpd3neph_sensorcpd3pwdvaisala_sensorcpd3wmtvaisala_sensorcpd3wxtv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inlet_switcher_state',
            old_name='inlet_state',
            new_name='inlet_selected',
        ),
        migrations.AddField(
            model_name='inlet_switcher_state',
            name='inlet_1_state',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='inlet_switcher_state',
            name='inlet_2_state',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='inlet_switcher_state',
            name='intet_name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
