# Generated by Django 3.1.3 on 2020-11-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_auto_20201123_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inlet_switcher_state',
            old_name='intet_name',
            new_name='inlet_name',
        ),
    ]
