# Generated by Django 3.1.3 on 2021-05-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_auto_20210512_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dma',
            name='impactor_press',
            field=models.FloatField(blank=True, db_column='Impactor Differential Pressure', null=True),
        ),
    ]
