# Generated by Django 3.1.3 on 2021-10-03 23:44

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=50, null=True, verbose_name='Page')),
                ('content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content')),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='app_images')),
            ],
        ),
    ]
