# Generated by Django 3.2.13 on 2022-06-27 23:24

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('research_objective', ckeditor_uploader.fields.RichTextUploadingField()),
                ('project_tentative_start_date', models.DateField()),
                ('project_duration', models.CharField(max_length=50)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=False, null=True)),
                ('show', models.BooleanField(default=False, null=True)),
                ('principal_investigator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
