# Generated by Django 4.0.4 on 2022-06-16 17:52

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='research_objective',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
