# Generated by Django 3.1.3 on 2021-06-21 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210621_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
