# Generated by Django 3.1.3 on 2021-07-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20210621_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
